extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - airbnb-typescript/base

parser: "@typescript-eslint/parser"

parserOptions:
  project: ./tsconfig.json

plugins:
  - "import"
  - "@typescript-eslint"

rules:
  "@typescript-eslint/explicit-function-return-type": error
  "no-useless-catch": off

ignorePatterns:
  - "/**/node_modules/*"
  - "/**/dist/*"
  - "/**/*.js"

root: true
