version: "3.7"

services:
  proxy:
    image: raul72/browsermob-proxy
    ports:
      - 8080:8080
      - 8081-8181:8081-8181
    environment:
      BMP_PROXY_PORT_RANGE: 8081-8181
  # docker-compose --profile test up --abort-on-container-exit
  test:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      TEST_SERVER_HOST_FOR_PROXY: test
      PROXY_HOST: proxy
    command: ["yarn", "test"]
    depends_on:
      - proxy
    profiles:
      - test

